name: Release BCD

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Version'
        # Default value if no value is explicitly provided
        default: '0.0.0'
        required: true
        type: string

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            owner: 'OnkarRuikar',
            repo: 'temp',
            workflow_id: 'target_workflow.yml',
            ref: 'main',
            inputs: {
              notes: "v5.3.10"
            },
          })
          console.log(result);
